/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jcmplayer_JCMPlayer */

#ifndef _Included_com_example_jcmplayer_JCMPlayer
#define _Included_com_example_jcmplayer_JCMPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkInitVideoPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkInitVideoPlayer
  (JNIEnv *, jobject);


/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkStartPlayerWithFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkStartPlayerWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkPauseVideoPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkPauseVideoPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkStopVideoPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkStopVideoPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkGetVideoSizeRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkGetVideoSizeRatio
        (JNIEnv *, jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkGetVideoSizeRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkGetVideoTotalSeconds
        (JNIEnv *, jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkSeekMedia
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkSeekMedia
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkInittGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkInitGL
(JNIEnv *, jobject,jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkPaintGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkPaintGL
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jcmplayer_JCMPlayer
 * Method:    ndkResizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_jcmplayer_JCMPlayer_ndkResizeGL
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
